name: Fupa Snack Cron Jobs

on:
  schedule:
    # Setiap hari jam 18:00 WIB (11:00 UTC) - untuk ALPA dan DELLTE
    - cron: '0 11 * * *'
    # Setiap hari jam 06:00 UTC (13:00 WIB) untuk CSVMD
    - cron: '0 6 * * *'
  workflow_dispatch: # Manual trigger

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run cron jobs
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: npm start